# Generated by Django 4.2.7 on 2025-03-13 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='镜像名称')),
                ('tag', models.CharField(max_length=50, verbose_name='镜像标签')),
                ('description', models.TextField(blank=True, null=True, verbose_name='镜像描述')),
                ('size', models.PositiveIntegerField(verbose_name='镜像大小(MB)')),
                ('registry', models.CharField(default='docker.io', max_length=200, verbose_name='镜像仓库')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docker_images', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': 'Docker镜像',
                'verbose_name_plural': 'Docker镜像',
                'ordering': ['-created_at'],
                'unique_together': {('registry', 'name', 'tag')},
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模型描述')),
                ('version', models.CharField(max_length=20, verbose_name='模型版本')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('training', '训练中'), ('completed', '已完成'), ('failed', '失败')], default='draft', max_length=20, verbose_name='状态')),
                ('parameters', models.JSONField(default=dict, verbose_name='训练参数')),
                ('metrics', models.JSONField(blank=True, default=dict, null=True, verbose_name='性能指标')),
                ('file', models.FileField(blank=True, null=True, upload_to='models/', verbose_name='模型文件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('training_started_at', models.DateTimeField(blank=True, null=True, verbose_name='训练开始时间')),
                ('training_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='训练完成时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='data_center.dataset', verbose_name='训练数据集')),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('log', models.TextField(blank=True, null=True, verbose_name='训练日志')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('docker_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to='training_center.dockerimage', verbose_name='Docker镜像')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='training_center.model', verbose_name='模型')),
            ],
            options={
                'verbose_name': '训练任务',
                'verbose_name_plural': '训练任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
