name: big_model_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip=23.0
  - pip:
    - django==4.2.7
    - djangorestframework==3.14.0
    - djangorestframework-simplejwt==5.3.0
    - django-cors-headers==4.3.0
    - django-filter==23.3
    - drf-yasg==1.21.7
    - psycopg2-binary==2.9.9
    - langchain==0.0.335
    - pgvector==0.2.3
    - python-dotenv==1.0.0
    - pandas==2.1.1
    - numpy==1.26.1
    - scikit-learn==1.3.2
    - transformers==4.35.0
    - torch>=2.2.0
    - Pillow==10.1.0
    - celery==5.3.4
    - redis==5.0.1
    - gunicorn==21.2.0 