# Generated by Django 4.2.7 on 2025-03-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['-created_at'], 'verbose_name': '知识库', 'verbose_name_plural': '知识库'},
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否公开'),
        ),
    ]
