# Generated by Django 4.2.7 on 2025-04-21 03:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='连接名称')),
                ('api_key', models.CharField(max_length=255, verbose_name='API密钥')),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='API密钥')),
                ('org_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='组织ID')),
                ('custom_headers', models.JSONField(blank=True, null=True, verbose_name='自定义请求头')),
                ('custom_params', models.JSONField(blank=True, null=True, verbose_name='自定义参数')),
                ('rate_limit', models.IntegerField(default=0, help_text='0表示无限制', verbose_name='速率限制(每分钟)')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认连接')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API连接',
                'verbose_name_plural': 'API连接',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='提供商名称')),
                ('provider_type', models.CharField(choices=[('openai', 'OpenAI'), ('google', 'Google AI'), ('baidu', '百度智能云'), ('azure', 'Azure OpenAI'), ('anthropic', 'Anthropic'), ('huggingface', 'HuggingFace'), ('custom', '自定义API')], max_length=50, verbose_name='提供商类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='api_providers/icons/', verbose_name='图标')),
                ('base_url', models.URLField(help_text='API的基础URL，如：https://api.openai.com/v1/', verbose_name='基础URL')),
                ('docs_url', models.URLField(blank=True, null=True, verbose_name='文档URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'API提供商',
                'verbose_name_plural': 'API提供商',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=255, verbose_name='调用端点')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='请求数据')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='响应数据')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败'), ('rate_limited', '超出速率限制'), ('error', '错误')], max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='使用的令牌数')),
                ('response_time', models.FloatField(verbose_name='响应时间(ms)')),
                ('user_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='用户IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='api_connector.apiconnection', verbose_name='API连接')),
            ],
            options={
                'verbose_name': 'API使用日志',
                'verbose_name_plural': 'API使用日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='apiconnection',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='api_connector.apiprovider', verbose_name='API提供商'),
        ),
        migrations.AlterUniqueTogether(
            name='apiconnection',
            unique_together={('name', 'provider')},
        ),
    ]
