# Generated by Django 4.2.7 on 2025-04-21 06:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_connector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='模型名称')),
                ('model_type', models.CharField(choices=[('text', '文本模型'), ('chat', '对话模型'), ('embedding', '嵌入模型'), ('image', '图像模型'), ('audio', '音频模型'), ('multimodal', '多模态模型'), ('other', '其他模型')], max_length=50, verbose_name='模型类型')),
                ('model_identifier', models.CharField(help_text='API中使用的实际模型标识符，如：gpt-4-turbo', max_length=255, verbose_name='模型标识符')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('max_tokens', models.IntegerField(default=4000, help_text='模型支持的最大令牌数（上下文窗口大小）', verbose_name='最大令牌数')),
                ('params_schema', models.JSONField(blank=True, default=dict, help_text='JSON格式的模型参数配置', verbose_name='参数配置')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认模型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='api_connector.apiprovider', verbose_name='API提供商')),
            ],
            options={
                'verbose_name': 'API模型',
                'verbose_name_plural': 'API模型',
                'ordering': ['provider', 'name'],
                'unique_together': {('provider', 'model_identifier')},
            },
        ),
    ]
