# Generated by Django 4.2.7 on 2025-03-13 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='应用名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='应用描述')),
                ('status', models.CharField(choices=[('stopped', '已停止'), ('running', '运行中'), ('error', '错误')], default='stopped', max_length=20, verbose_name='状态')),
                ('endpoint', models.URLField(blank=True, null=True, verbose_name='API端点')),
                ('config', models.JSONField(default=dict, verbose_name='配置参数')),
                ('resource_usage', models.JSONField(blank=True, default=dict, null=True, verbose_name='资源占用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deployed_at', models.DateTimeField(blank=True, null=True, verbose_name='部署时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='training_center.model', verbose_name='使用的模型')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='插件名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='插件描述')),
                ('version', models.CharField(max_length=20, verbose_name='插件版本')),
                ('file', models.FileField(upload_to='plugins/', verbose_name='插件文件')),
                ('compatibility', models.JSONField(default=dict, verbose_name='兼容性信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '插件',
                'verbose_name_plural': '插件',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'version', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('config', models.JSONField(blank=True, default=dict, null=True, verbose_name='插件配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_plugins', to='app_center.application', verbose_name='应用')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_plugins', to='app_center.plugin', verbose_name='插件')),
            ],
            options={
                'verbose_name': '应用插件关联',
                'verbose_name_plural': '应用插件关联',
                'ordering': ['-created_at'],
                'unique_together': {('application', 'plugin')},
            },
        ),
    ]
